MOTIVATIONAL_QUOTES = [
    "Stay hard! - David Goggins",
    "If you want to be tougher, be tougher. - David Goggins",
    "The only easy day was yesterday. - Navy SEALs",
    "Discipline equals freedom. - Jocko Willink",
    "Get after it. - Jocko Willink",
    "Turn your wounds into wisdom. - Oprah Winfrey",
    "You become what you believe. - Oprah Winfrey",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Everything you've ever wanted is on the other side of fear. - George Addair",
    "Whether you think you can or you think you can't, you're right. - Henry Ford",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
    "Dreams don't work unless you do. - John C. Maxwell",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "The pain you feel today will be the strength you feel tomorrow. - Unknown",
    "It's not about perfect. It's about effort. - Jillian Michaels",
    "Fall seven times, stand up eight. - Japanese Proverb",
    "The only bad workout is the one that didn't happen. - Unknown",
    "Your body can stand almost anything. It's your mind that you have to convince. - Unknown",
    "The harder you push yourself, the more you can take. - David Goggins",
    "Embrace the suffering. - David Goggins",
    "The mind is the most powerful weapon you have. - Jocko Willink",
    "Owning your own story is the bravest thing you'll ever do. - Brené Brown",
    "When we learn how to become resilient, we learn how to embrace the beautifully broad spectrum of the human experience. - Jaeda DeWalt",
    "Life's challenges are not supposed to paralyze you; they're supposed to help you discover who you are. - Bernice Johnson Reagon",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "Strength does not come from physical capacity. It comes from an indomitable will. - Mahatma Gandhi",
    "The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy. - Martin Luther King Jr.",
    "Perseverance is not a long race; it is many short races one after the other. - Walter Elliot",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "The brick walls are there for a reason. The brick walls are not there to keep us out. The brick walls are there to give us a chance to show how badly we want something. Because the brick walls are there to stop the people who don't want it badly enough. They're there to stop the other people. - Randy Pausch",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Happiness is not by chance, but by choice. - Jim Rohn",
    "The only way to find true happiness is to risk being completely cut open. - Chuck Palahniuk",
    "Stay close to anything that makes you glad you are alive. - Hafiz",
    "Start each day with a positive thought and a grateful heart. - Roy T. Bennett",
    "Let your unique awesomeness and positive energy inspire confidence in others. - Unknown",
    "Wherever you go, no matter what the weather, always bring your own sunshine. - Anthony J. D'Angelo",
    "No matter what you’re going through, there’s a light at the end of the tunnel. - Demi Lovato",
    "You do not find the happy life. You make it. - Camilla Eyring Kimball",
    "Positive anything is better than negative nothing. - Elbert Hubbard",
    "Keep your face to the sunshine and you cannot see a shadow. - Helen Keller",
    "Success is the sum of small efforts, repeated day-in and day-out. - Robert Collier",
    "Only in the darkness can you see the stars. - Martin Luther King Jr.",
    "Happiness is the only thing that multiplies when you share it. - Albert Schweitzer",
    "The more you praise and celebrate your life, the more there is in life to celebrate. - Oprah Winfrey",
    "The most wasted of days is one without laughter. - E.E. Cummings",
    "Keep looking up… that’s the secret of life. - Snoopy",
    "It makes a big difference in your life when you stay positive. - Ellen DeGeneres",
    "You are the artist of your own life. Don’t hand the paintbrush to anyone else. - Unknown",
    "You are never too old to set another goal or dream a new dream. - C.S. Lewis",
    "Believe you can and you’re halfway there. - Theodore Roosevelt",
    "Act as if what you do makes a difference. It does. - William James",
    "In every day, there are 1,440 minutes. That means we have 1,440 daily opportunities to make a positive impact. - Les Brown",
    "The best way to predict the future is to create it. - Peter Drucker",
    "A warm smile is the universal language of kindness. - William Arthur Ward",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "You have to be odd to be number one. - Dr. Seuss",
    "If opportunity doesn’t knock, build a door. - Milton Berle",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Don’t wait for the right opportunity. Create it. - George Bernard Shaw",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "Do not let what you cannot do interfere with what you can do. - John Wooden",
    "You cannot have a positive life and a negative mind. - Joyce Meyer",
    "Your positive action combined with positive thinking results in success. - Shiv Khera",
    "In order to carry a positive action we must develop here a positive vision. - Dalai Lama",
    "Happiness is an inside job. Don’t assign anyone else that much power over your life. - Mandy Hale",
    "Happiness is not something you postpone for the future; it is something you design for the present. - Jim Rohn",
    "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change. - Unknown",
    "Happiness often sneaks in through a door you didn’t know you left open. - John Barrymore",
    "The only time you fail is when you fall down and stay down. - Stephen Richards",
    "You can, you should, and if you’re brave enough to start, you will. - Stephen King",
    "When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love. - Marcus Aurelius",
    "Stay positive. Better days are on their way. - Unknown",
    "Work hard, stay positive, and get up early. It’s the best part of the day. - George Allen Sr.",
    "Choose to be optimistic, it feels better. - Dalai Lama",
    "When things go wrong, don’t go with them. - Elvis Presley",
    "The only thing more contagious than a good attitude is a bad one. - Unknown",
    "There is nothing impossible to him who will try. - Alexander the Great",
    "I will go anywhere as long as it’s forward. - David Livingston",
    "Even if you’re on the right track, you’ll get run over if you just sit there. - Will Rogers",
    "Always be a first-rate version of yourself, instead of a second-rate version of somebody else. - Judy Garland",
    "Light tomorrow with today. - Elizabeth Barrett Browning",
    "It isn’t where you came from. It’s where you’re going that counts. - Ella Fitzgerald",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "Perfection is not attainable, but if we chase perfection we can catch excellence. - Vince Lombardi",
    "You are never too old to reinvent yourself. - Steve Harvey",
    "It’s not about how hard you can hit; it’s about how hard you can get hit and keep moving forward. - Sylvester Stallone",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "No act of kindness, no matter how small, is ever wasted. - Aesop",
    "When you know better, you do better. - Maya Angelou",
    "You don’t need a new day to start over, you only need a new mindset. - Hazel Hira Ozbek",
    "Don’t quit. Suffer now and live the rest of your life as a champion. - Muhammad Ali",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
    "In the middle of every difficulty lies opportunity. - Albert Einstein",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "A winner is a dreamer who never gives up. - Nelson Mandela",
    "Life has no limitations, except the ones you make. - Les Brown",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "What we think, we become. - Buddha",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "Success isn’t about how much money you make, it’s about the difference you make in people’s lives. - Michelle Obama",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "We must embrace pain and burn it as fuel for our journey. - Kenji Miyazawa",
    "We don’t see things as they are, we see them as we are. - Anais Nin",
    "You’re off to great places, today is your day. Your mountain is waiting, so get on your way. - Dr. Seuss",
    "Live life to the fullest, and focus on the positive. - Matt Cameron",
    "It takes sunshine and rain to make a rainbow. There would be no rainbows without sunshine and rain. - Roy T. Bennett",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Life is not about waiting for the storm to pass but about learning to dance in the rain. - Vivian Greene",
    "You are capable of amazing things. - Unknown",
    "Life is either a daring adventure or nothing at all. - Helen Keller",
    "Spread love everywhere you go. Let no one ever come to you without leaving happier. - Mother Teresa",
    "The more you give away, the more happy you become. Why fit in when you were born to stand out? - Dr. Seuss",
    "Success is a state of mind. If you want success, start thinking of yourself as a success. - Joyce Brothers",
    "Find a place inside where there’s joy, and the joy will burn out the pain. - Joseph Campbell",
    "Happiness is a direction, not a place. - Sydney J. Harris",
    "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
    "Positive anything is better than negative nothing. - Elbert Hubbard",
    "Happiness depends upon ourselves. - Aristotle",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "If you can dream it, you can do it. - Walt Disney",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "The best way to predict the future is to create it. - Peter Drucker",
    "Success is going from failure to failure without losing your enthusiasm. - Winston Churchill",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Keep going. Everything you need will come to you at the perfect time. - Unknown",
    "Every moment is a fresh beginning. - T.S. Eliot",
    "Do what you feel in your heart to be right – for you’ll be criticized anyway. - Eleanor Roosevelt",
    "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Don't wait. The time will never be just right. - Napoleon Hill",
    "You are enough just as you are. - Meghan Markle",
    "Difficulties in life are intended to make us better, not bitter. - Dan Reeves",
    "The more you praise and celebrate your life, the more there is in life to celebrate. - Oprah Winfrey",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
    "The best revenge is massive success. - Frank Sinatra",
    "Be kind whenever possible. It is always possible. - Dalai Lama",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Dream big and dare to fail. - Norman Vaughan",
    "Nothing is impossible, the word itself says 'I'm possible!' - Audrey Hepburn",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "Turn your wounds into wisdom. - Oprah Winfrey",
    "Don't count the days, make the days count. - Muhammad Ali",
    "Failure is simply the opportunity to begin again, this time more intelligently. - Henry Ford",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
    "The harder you work for something, the greater you’ll feel when you achieve it. - Unknown",
    "Success doesn’t come to you, you go to it. - Marva Collins",
    "The mind is everything. What you think, you become. - Buddha",
    "Believe in your infinite potential. Your only limitations are those you set upon yourself. - Roy T. Bennett",
    "Life is what we make it, always has been, always will be. - Grandma Moses",
    "Don’t let yesterday take up too much of today. - Will Rogers",
    "Every day may not be good, but there is something good in every day. - Unknown",
    "Dream big. Start small. Act now. - Robin Sharma",
    "Don’t let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Life is short, and it’s up to you to make it sweet. - Sarah Louise Delany",
    "Success isn’t about the end result, it’s about what you learn along the way. - Vera Wang",
    "There is no limit to what you can achieve, except the limits you place on your own thinking. - Brian Tracy",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "The secret of getting ahead is getting started. - Mark Twain",
    "You are enough just as you are. - Meghan Markle",
    "It is never too late to be what you might have been. - George Eliot",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
    "In the middle of every difficulty lies opportunity. - Albert Einstein",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "Believe you can and you’re halfway there. - Theodore Roosevelt",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "Turn your wounds into wisdom. - Oprah Winfrey",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Believe in your infinite potential. Your only limitations are those you set upon yourself. - Roy T. Bennett",
    "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
    "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change. - Unknown",
    "Dream big and dare to fail. - Norman Vaughan",
    "Happiness depends upon ourselves. - Aristotle",
    "What we think, we become. - Buddha",
    "The best way to predict the future is to create it. - Peter Drucker",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
    "Act as if what you do makes a difference. It does. - William James",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success isn’t about how much money you make, it’s about the difference you make in people’s lives. - Michelle Obama",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "Success is the sum of small efforts, repeated day-in and day-out. - Robert Collier",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "Your limitation—it’s only your imagination. - Unknown",
    "Push yourself, because no one else is going to do it for you. - Unknown",
    "Great things never come from comfort zones. - Unknown",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
    "We must embrace pain and burn it as fuel for our journey. - Kenji Miyazawa",
    "You can, you should, and if you’re brave enough to start, you will. - Stephen King",
    "Your positive action combined with positive thinking results in success. - Shiv Khera",
    "The best revenge is massive success. - Frank Sinatra",
    "Keep going. Everything you need will come to you at the perfect time. - Unknown",
    "Start each day with a positive thought and a grateful heart. - Roy T. Bennett",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "Stay positive, work hard, make it happen. - Unknown",
    "Happiness is not a goal; it is a by-product. - Eleanor Roosevelt",
    "The secret to getting ahead is getting started. - Mark Twain",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
    "We become what we think about. - Earl Nightingale",
    "Don't let the fear of striking out hold you back. - Babe Ruth",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "Hard work beats talent when talent doesn't work hard. - Tim Notke",
    "The best way to predict the future is to invent it. - Alan Kay",
    "Success is how high you bounce when you hit bottom. - George S. Patton",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
    "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
    "Failure is not the opposite of success; it’s part of success. - Arianna Huffington",
    "You cannot swim for new horizons until you have courage to lose sight of the shore. - William Faulkner",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "What you do speaks so loudly that I cannot hear what you say. - Ralph Waldo Emerson",
    "Be a positive energy trampoline – absorb what you need and rebound more back. - Dave Carolan",
    "To live will be an awfully big adventure. - J.M. Barrie",
    "Success is the result of preparation, hard work, and learning from failure. - Colin Powell",
    "There are no secrets to success. It is the result of preparation, hard work, and learning from failure. - Colin Powell",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Don’t wait. The time will never be just right. - Napoleon Hill",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "Act as if what you do makes a difference. It does. - William James",
    "Believe you can and you’re halfway there. - Theodore Roosevelt",
    "Do what you can with all you have, wherever you are. - Theodore Roosevelt",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Fall seven times, stand up eight. - Japanese Proverb",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "The best revenge is massive success. - Frank Sinatra",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "No one is to blame for your future situation but yourself. If you want to be successful, then become “Successful.” - Jaymin Shah",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "If you can’t outplay them, outwork them. - Ben Hogan",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "You must expect great things of yourself before you can do them. - Michael Jordan",
    "Limit your 'always' and your 'nevers.' - Amy Poehler",
    "When you reach the end of your rope, tie a knot in it and hang on. - Franklin D. Roosevelt",
    "If opportunity doesn’t knock, build a door. - Milton Berle",
    "The most beautiful things in the world cannot be seen or even touched. They must be felt with the heart. - Helen Keller",
    "It is during our darkest moments that we must focus to see the light. - Aristotle",
    "Live each day as if your life had just begun. - Johann Wolfgang Von Goethe",
    "Believe in your dreams. They were given to you for a reason. - Katrina Mayer",
    "You can't cross the sea merely by standing and staring at the water. - Rabindranath Tagore",
    "It always seems impossible until it is done. - Nelson Mandela",
    "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Action is the foundational key to all success. - Pablo Picasso",
    "Opportunities don't happen, you create them. - Chris Grosser",
    "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Inspiration does exist, but it must find you working. - Pablo Picasso",
    "Our greatest glory is not in never falling, but in rising every time we fall. - Confucius",
    "If you want to achieve greatness stop asking for permission. - Unknown",
    "Do one thing every day that scares you. - Eleanor Roosevelt",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "The best way to predict the future is to create it. - Abraham Lincoln",
    "It is our choices, that show what we truly are, far more than our abilities. - J.K. Rowling",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "Don't count the days, make the days count. - Muhammad Ali",
    "You don’t need to see the whole staircase, just take the first step. - Martin Luther King Jr.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Doubt kills more dreams than failure ever will. - Suzy Kassem",
    "Do something today that your future self will thank you for. - Unknown",
    "Dream it. Wish it. Do it. - Unknown",
    "Don't wait for opportunity. Create it. - Unknown",
    "Little things make big days. - Unknown",
    "Don't stop when you're tired. Stop when you're done. - Unknown",
    "Wake up with determination. Go to bed with satisfaction. - Unknown",
    "Do something today that your future self will thank you for. - Unknown",
    "It's going to be hard, but hard does not mean impossible. - Unknown",
    "Push yourself, because no one else is going to do it for you. - Unknown",
    "Success doesn’t just find you. You have to go out and get it. - Unknown",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "To accomplish great things, we must not only act, but also dream; not only plan, but also believe. - Anatole France",
    "Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds. - Orison Swett Marden",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "It is our choices that show what we truly are, far more than our abilities. - J.K. Rowling",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Success is a journey, not a destination. - Ben Sweetland",
    "Go confidently in the direction of your dreams! Live the life you've imagined. - Henry David Thoreau",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "We become what we think about. - Earl Nightingale",
    "Whether you think you can or think you can’t, you’re right. - Henry Ford",
    "Too many of us are not living our dreams because we are living our fears. - Les Brown",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "Your life does not get better by chance, it gets better by change. - Jim Rohn",
    "Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do. - Unknown",
    "You must expect great things of yourself before you can do them. - Michael Jordan",
    "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact. - William James",
    "Life is what we make it, always has been, always will be. - Grandma Moses",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Act as if what you do makes a difference. It does. - William James",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Success is the sum of small efforts, repeated day-in and day-out. - Robert Collier",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
    "Opportunities don’t happen, you create them. - Chris Grosser",
    "If you really look closely, most overnight successes took a long time. - Steve Jobs",
    "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Don’t let yesterday take up too much of today. - Will Rogers",
    "Failure will never overtake me if my determination to succeed is strong enough. - Og Mandino",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Whatever the mind of man can conceive and believe, it can achieve. - Napoleon Hill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Believe you can and you’re halfway there. - Theodore Roosevelt",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "Success is how high you bounce when you hit bottom. - George S. Patton",
    "You can, you should, and if you’re brave enough to start, you will. - Stephen King",
    "Don’t wait for opportunity. Create it. - Unknown",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
    "When we strive to become better than we are, everything around us becomes better too. - Paulo Coelho",
    "Be so good they can’t ignore you. - Steve Martin",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Your limitation—it’s only your imagination. - Unknown",
    "Dream big and dare to fail. - Norman Vaughan",
    "Do one thing every day that scares you. - Eleanor Roosevelt",
    "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "The secret of getting ahead is getting started. - Mark Twain",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "You don’t need to see the whole staircase, just take the first step. - Martin Luther King Jr.",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "The best way to predict the future is to create it. - Abraham Lincoln",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Don’t let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Great things never come from comfort zones. - Unknown",
    "Dream it. Wish it. Do it. - Unknown",
    "It’s going to be hard, but hard does not mean impossible. - Unknown",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Work hard in silence, let success be your noise. - Frank Ocean",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "Stay positive, work hard, make it happen. - Unknown",
    "Believe you can and you’re halfway there. - Theodore Roosevelt",
    "Start each day with a positive thought and a grateful heart. - Roy T. Bennett",
    "Do something today that your future self will thank you for. - Unknown",
    "You are enough just as you are. - Meghan Markle",
    "It’s not about how hard you hit. It’s about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "You only fail when you stop trying. - Unknown",
    "Push yourself, because no one else is going to do it for you. - Unknown",
    "Success doesn’t just find you. You have to go out and get it. - Unknown",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "The harder you work for something, the greater you’ll feel when you achieve it. - Unknown",
    "The key to success is to focus on goals, not obstacles. - Unknown",
    "Don’t wait for opportunity. Create it. - Unknown",
    "You don’t need to see the whole staircase, just take the first step. - Martin Luther King Jr.",
    "Little things make big days. - Unknown",
    "The harder the struggle, the more glorious the triumph. - Unknown",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Opportunities don't happen, you create them. - Chris Grosser",
    "Your limitation—it’s only your imagination. - Unknown",
    "Great things never come from comfort zones. - Unknown",
    "Dream bigger. Do bigger. - Unknown",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "Success isn't always about greatness. It's about consistency. - Dwayne Johnson",
    "You must expect great things of yourself before you can do them. - Michael Jordan",
    "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Be so good they can't ignore you. - Steve Martin",
    "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "If you really want to do something, you'll find a way. If you don't, you'll find an excuse. - Jim Rohn",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success doesn't come to you, you go to it. - Marva Collins",
    "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
    "Don't count the days, make the days count. - Muhammad Ali",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "Success is the sum of small efforts, repeated day-in and day-out. - Robert Collier",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Do what you feel in your heart to be right, for you'll be criticized anyway. - Eleanor Roosevelt",
    "The best way to predict the future is to create it. - Abraham Lincoln",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Doubt kills more dreams than failure ever will. - Suzy Kassem",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The key to success is to start before you are ready. - Marie Forleo",
    "You only fail when you stop trying. - Unknown",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Opportunities are usually disguised as hard work, so most people don't recognize them. - Ann Landers",
    "The harder you work, the luckier you get. - Gary Player",
    "Failure is the condiment that gives success its flavor. - Truman Capote",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
    "If you set your goals ridiculously high and it’s a failure, you will fail above everyone else’s success. - James Cameron",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "I never dreamed about success. I worked for it. - Estée Lauder",
    "Success is getting what you want, happiness is wanting what you get. - W.P. Kinsella",
    "Happiness lies in the joy of achievement and the thrill of creative effort. - Franklin D. Roosevelt",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Believe in yourself and all that you are. - Christian D. Larson",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "Success is the sum of small efforts, repeated day-in and day-out. - Robert Collier",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Don't let yesterday take up too much of today. - Will Rogers",
    "You must expect great things of yourself before you can do them. - Michael Jordan",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "The secret of getting ahead is getting started. - Mark Twain",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact. - William James",
    "Dream big and dare to fail. - Norman Vaughan",
    "Keep your eyes on the stars, and your feet on the ground. - Theodore Roosevelt",
    "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome. - Booker T. Washington",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "The best way to predict the future is to create it. - Peter Drucker",
    "Perseverance is not a long race; it is many short races one after the other. - Walter Elliot",
    "Life is what happens when you’re busy making other plans. - John Lennon",
    "Get busy living or get busy dying. - Stephen King",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "In the end, it’s not the years in your life that count. It’s the life in your years. - Abraham Lincoln",
    "Live in the sunshine, swim the sea, drink the wild air. - Ralph Waldo Emerson",
    "The best way to predict your future is to create it. - Abraham Lincoln",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "Life is either a daring adventure or nothing at all. - Helen Keller",
    "In three words I can sum up everything I’ve learned about life: it goes on. - Robert Frost",
    "Don’t cry because it’s over, smile because it happened. - Dr. Seuss",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "Keep calm and carry on. - Winston Churchill",
    "Happiness depends upon ourselves. - Aristotle",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "The only impossible journey is the one you never begin. - Tony Robbins",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "Act as if what you do makes a difference. It does. - William James",
    "We must not allow other people’s limited perceptions to define us. - Virginia Satir",
    "I have learned over the years that when one’s mind is made up, this diminishes fear. - Rosa Parks",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Do what you feel in your heart to be right – for you’ll be criticized anyway. - Eleanor Roosevelt",
    "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
    "Believe you can and you’re halfway there. - Theodore Roosevelt",
    "No one can make you feel inferior without your consent. - Eleanor Roosevelt",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Turn your wounds into wisdom. - Oprah Winfrey",
    "Whatever you are, be a good one. - Abraham Lincoln",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
    "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt",
    "The best revenge is massive success. - Frank Sinatra",
    "The unexamined life is not worth living. - Socrates",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
    "Don’t count the days, make the days count. - Muhammad Ali",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "May you live all the days of your life. - Jonathan Swift",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "Dream big and dare to fail. - Norman Vaughan",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "The best way to predict the future is to invent it. - Alan Kay",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
    "It is our choices that show what we truly are, far more than our abilities. - J.K. Rowling",
    "We must let go of the life we have planned, so as to accept the one that is waiting for us. - Joseph Campbell",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away. - Maya Angelou",
    "Life isn’t about finding yourself. Life is about creating yourself. - George Bernard Shaw",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "To live will be an awfully big adventure. - J.M. Barrie",
    "In order to write about life first you must live it. - Ernest Hemingway",
    "To succeed in life, you need two things: ignorance and confidence. - Mark Twain",
    "Good friends, good books, and a sleepy conscience: this is the ideal life. - Mark Twain",
    "Do not let making a living prevent you from making a life. - John Wooden",
    "Life is short, and it is up to you to make it sweet. - Sarah Louise Delany",
    "The longer I live, the more I realize the impact of attitude on life. - Charles R. Swindoll",
    "Keep smiling, because life is a beautiful thing and there’s so much to smile about. - Marilyn Monroe",
    "Life’s tragedy is that we get old too soon and wise too late. - Benjamin Franklin",
    "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy",
    "Believe you can and you’re halfway there. - Theodore Roosevelt",
    "Don’t cry because it’s over, smile because it happened. - Dr. Seuss",
    "Act as if what you do makes a difference. It does. - William James",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "You are enough just as you are. - Meghan Markle",
    "Everything you can imagine is real. - Pablo Picasso",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "Be yourself, everyone else is already taken. - Oscar Wilde",
    "You’re off to great places! Today is your day! Your mountain is waiting, so get on your way! - Dr. Seuss",
    "You have to be odd to be number one. - Dr. Seuss",
    "Don’t let yesterday take up too much of today. - Will Rogers",
    "The people who are crazy enough to think they can change the world are the ones who do. - Steve Jobs",
    "Be a voice, not an echo. - Unknown",
    "Why fit in when you were born to stand out? - Dr. Seuss",
    "It’s not what happens to you, but how you react to it that matters. - Epictetus",
    "You are braver than you believe, stronger than you seem, and smarter than you think. - A.A. Milne",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Your only limit is you. - Unknown",
    "Stay weird, stay different. - Graham Moore",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "You’re only given a little spark of madness. You mustn’t lose it. - Robin Williams",
    "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
    "In the end, we only regret the chances we didn’t take. - Lewis Carroll",
    "No one is you, and that is your superpower. - Unknown",
    "Dream big. Start small. Act now. - Robin Sharma",
    "The things that make me different are the things that make me. - A.A. Milne",
    "Success is the ability to go from one failure to another with no loss of enthusiasm. - Winston Churchill",
    "If you want to fly, you have to give up the things that weigh you down. - Toni Morrison",
    "You don’t have to be perfect to be amazing. - Unknown",
    "Always be a first-rate version of yourself, instead of a second-rate version of somebody else. - Judy Garland",
    "Don’t count the days, make the days count. - Muhammad Ali",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "Mistakes are proof that you are trying. - Unknown",
    "Never let anyone dull your sparkle. - Unknown",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "To live will be an awfully big adventure. - J.M. Barrie",
    "If you’re going through hell, keep going. - Winston Churchill",
    "Be so good they can’t ignore you. - Steve Martin",
    "Some people want it to happen, some wish it would happen, others make it happen. - Michael Jordan",
    "Don’t tell me the sky’s the limit when there are footprints on the moon. - Paul Brandt",
    "Do or do not, there is no try. - Yoda",
    "Dream as if you’ll live forever. Live as if you’ll die today. - James Dean",
    "Be the weird you wish to see in the world. - Unknown",
    "Don’t let what you cannot do interfere with what you can do. - John Wooden",
    "It’s kind of fun to do the impossible. - Walt Disney",
    "Don’t cry because it’s over, smile because it happened. - Dr. Seuss",
    "Never give up on something that you can’t go a day without thinking about. - Winston Churchill",
    "Live in such a way that if someone spoke badly of you, no one would believe it. - Unknown",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "You can’t use up creativity. The more you use, the more you have. - Maya Angelou",
    "Life isn’t about waiting for the storm to pass, it’s about learning how to dance in the rain. - Vivian Greene",
    "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
    "You can never cross the ocean until you have the courage to lose sight of the shore. - Christopher Columbus",
    "Don’t be afraid to be yourself. - Unknown",
    "You are never too old to set another goal or dream a new dream. - C.S. Lewis",
    "Sometimes you win, sometimes you learn. - John Maxwell",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "Being different isn’t a bad thing. It means you’re brave enough to be yourself. - Luna Lovegood",
    "There are no shortcuts to any place worth going. - Beverly Sills",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Don’t wait. The time will never be just right. - Napoleon Hill",
    "Do one thing every day that scares you. - Eleanor Roosevelt",
    "Sometimes you have to create your own sunshine. - Unknown",
    "Life is too short to be anything but happy. - Unknown",
    "Shoot for the moon. Even if you miss, you’ll land among the stars. - Norman Vincent Peale",
    "You have to be unique, and different, and shine in your own way. - Lady Gaga",
    "Work hard, be kind, and amazing things will happen. - Conan O’Brien",
    "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
    "If you can’t be kind, be quiet. - Unknown",
    "Happiness can be found even in the darkest of times if one only remembers to turn on the light. - Albus Dumbledore",
    "If you want to go fast, go alone. If you want to go far, go together. - African Proverb",
    "Stop being afraid of what could go wrong and start being excited about what could go right. - Tony Robbins",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "Live like you’re at the bottom, even if you’re at the top. - Jonas Brothers",
    "Stay hungry, stay foolish. - Steve Jobs",
    "No one ever made a difference by being like everyone else. - P.T. Barnum"
]