MOTIVATIONAL_QUOTES = [
    "Stay hard! - David Goggins",
    "If you want to be tougher, be tougher. - David Goggins",
    "The only easy day was yesterday. - Navy SEALs",
    "Discipline equals freedom. - Jocko Willink",
    "Get after it. - Jocko Willink",
    "Turn your wounds into wisdom. - Oprah Winfrey",
    "You become what you believe. - Oprah Winfrey",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Everything you've ever wanted is on the other side of fear. - George Addair",
    "Whether you think you can or you think you can't, you're right. - Henry Ford",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
    "Dreams don't work unless you do. - John C. Maxwell",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "The pain you feel today will be the strength you feel tomorrow. - Unknown",
    "It's not about perfect. It's about effort. - Jillian Michaels",
    "Fall seven times, stand up eight. - Japanese Proverb",
    "The only bad workout is the one that didn't happen. - Unknown",
    "Your body can stand almost anything. It's your mind that you have to convince. - Unknown",
    "The harder you push yourself, the more you can take. - David Goggins",
    "Embrace the suffering. - David Goggins",
    "The mind is the most powerful weapon you have. - Jocko Willink",
    "Owning your own story is the bravest thing you'll ever do. - Brené Brown",
    "When we learn how to become resilient, we learn how to embrace the beautifully broad spectrum of the human experience. - Jaeda DeWalt",
    "Life's challenges are not supposed to paralyze you; they're supposed to help you discover who you are. - Bernice Johnson Reagon",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "Strength does not come from physical capacity. It comes from an indomitable will. - Mahatma Gandhi",
    "The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy. - Martin Luther King Jr.",
    "Perseverance is not a long race; it is many short races one after the other. - Walter Elliot",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "The brick walls are there for a reason. The brick walls are not there to keep us out. The brick walls are there to give us a chance to show how badly we want something. Because the brick walls are there to stop the people who don't want it badly enough. They're there to stop the other people. - Randy Pausch",
    "It always seems impossible until it's done. - Nelson Mandela"
]